### PR TITLE
When parsing response with regex, check resulting array of matches be…

### LINKED ISSUE #11: Undefined offset: 0 in .../src/Client.php on line 244
Hi, 

First of all, I really like this package. 

I use this package to mostly interface with queues. When creating an invalid queue (eg. queue type doesn't exist or queue name is already used), I get the notice: 

> PHP Notice:  Undefined offset: 0 in .../evilfreelancer/routeros-api-php/src/Client.php on line 244

Here's line 244: https://github.com/EvilFreelancer/routeros-api-php/blob/master/src/Client.php#L244

When creating a queue with a name that already exists, dumping `$matches` after line 242 of Client.php prints these two arrays after calling `$client->read()`:

```
array:3 [
  0 => array:1 [
    0 => "=message=failure: already have such name"
  ]
  1 => array:1 [
    0 => "message"
  ]
  2 => array:1 [
    0 => "failure: already have such name"
  ]
]
array:3 [
  0 => []
  1 => []
  2 => []
]
```
Then two notices about the undefined offset. I think it is failing on the second array where the response would be '!done'. `$match[1][0]` and `$match[2][0]` are not defined.

Should an exception be thrown instead?

I'm using Laravel and it throws an exception on notices by default.

### PR DESCRIPTION
**Pull request by jmross**
…tter to avoid undefined index notices

Closes #11

### CODE REVIEW

File: src/Client.php [hunk 1]
```diff
@@ -240,15 +240,15 @@ private function parseResponse(array $response): array
                         // If we have lines after current one
                         if (isset($response[$j])) {
                             $this->pregResponse($response[$j], $matches);
-                            if (!empty($matches)) {
+                            if (isset($matches[1][0]) && isset($matches[2][0])) {
```
Comment (EvilFreelancer) [inline src/Client.php]: Please replace it to this code:
```
if (isset($matches[1][0], $matches[2][0])) {
```
Same for line below
